AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hello-world

  Sample SAM Template for hello-world
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DonutListFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: donut-list/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        ListRequest:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list
            Method: get
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref DonutTable
      Environment:
        Variables:
          TABLE_NAME: !Ref DonutTable
  DonutTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      Tags:
        Name: donutlist
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DonutListApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/list/"
  DonutListFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DonutListFunction.Arn
  DonutListFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt DonutListFunctionRole.Arn
